class Permissions:
    USER_READ = "user.read"
    USER_UPDATE = "user.update"
    USER_DELETE = "user.delete"
    AUTH_LOGIN = "auth.login"
    BILLING_READ = "billing.read"
    BILLING_MANAGE = "billing.manage"
    NOTIFICATION_READ = "notification.read"
    NOTIFICATION_SEND = "notification.send"
    ADMIN_ACCESS = "admin.access"
